# Site settings
title: "Johnny Hopkins"
author_name: "Johnny Hopkins"
job_title: "Data Science Portfolio"
email: "johnny@example.com"
description: "Hi I'm Johnny, and I'm a Data Scientist. My portfolio focuses on interesting, value-adding projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
location: "London, UK"

# URLs
baseurl: ""
url: ""

# Social media
github_username: "johnnyhopkins"
linkedin_username: "johnny-hopkins"

# Company branding
company_name: "CyberSecurityRockstar"
company_url: "https://cybersecurityrockstar.com"
footer_logo: "/assets/images/footer-logo.jpg" # Add your company logo here

# Theme color - Available options: blue, green, red, purple, orange, pink, teal, dark, clean
theme_color: "blue"

# FLEXIBLE RESUME SYSTEM - Choose what works for you!
resume_options:
  # Option 1: PDF Download (Recommended for professional use)
  pdf_enabled: true # Set to true to show PDF download option
  pdf_url: "/assets/resume.pdf" # Path to your PDF file
  pdf_label: "Download Resume (PDF)" # Label for PDF button

  # Option 2: Auto-Generated Resume
  generated_enabled: true # Set to true to show generated resume option
  generated_label: "View Resume" # Label for generated resume button

  # Display Options
  show_both: true # true = show both buttons, false = show only the first available option
  primary_option: "pdf" # "pdf" or "generated" - which one to show first/solo

# Legacy support (still works but use resume_options above for more control)
# resume_url: "/assets/resume.pdf"     # Old way - use resume_options instead

# FIXED: Theme switcher control
show_theme_switcher: false # Set to true to show the theme switcher widget

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
